name: Publish website at euroscipy.org

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: make install-ci

    - name: Build website
      run: |
        make html
        echo "euroscipy.org" > ./output/CNAME

    - name: Update the main gh-page website
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        commit_message: "[ci skip] ${{ github.event.head_commit.message }}"
